[pacman]
install = ['cava']
[flatpak]
install = ['app.zen_browser.zen']
[git]
clone = ['https://github.com/WeirdTreeThing/chromebook-linux-audio.git']
location = ['./git']
[wget]
file = ['https://raw.githubusercontent.com/4urora3night/dotfiles/refs/heads/main/pac.toml']
location = ['./wget']
